In [4]:
import numpy as np

add(a, b)

In [5]:
var = np.array([1, 2, 3, 4, 5])
print(var)
varadd = var + 3
print(varadd)
varadd2 = var + varadd
print(varadd2)

[1 2 3 4 5]
[4 5 6 7 8]
[ 5  7  9 11 13]


Subtract - subtract(a, b)

In [7]:
var = np.array([1, 2, 3, 4,5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varsub = var - var2
print(varsub)

[1 2 3 4 5]
[1 2 3 4 5]
[0 0 0 0 0]


Multiply - multiply(a, b)

In [8]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varmul = var * var2
print(varmul)


[1 2 3 4 5]
[1 2 3 4 5]
[ 1  4  9 16 25]


Divide - divide(a, b)

In [9]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
vardiv = var / var2
print(vardiv)


[1 2 3 4 5]
[1 2 3 4 5]
[1. 1. 1. 1. 1.]


Power - power(a, b)

In [10]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varpow = var ** var2
print(varpow)

[1 2 3 4 5]
[1 2 3 4 5]
[   1    4   27  256 3125]


Modulo - mod(a, b)

In [11]:
var =   np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varmod = var % var2
print(varmod)

[1 2 3 4 5]
[1 2 3 4 5]
[0 0 0 0 0]


Reciprocal - reciprocal(a, b)

In [13]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
# reciprocal
varrec = 1 / var
print(varrec)


[1 2 3 4 5]
[1 2 3 4 5]
[1.         0.5        0.33333333 0.25       0.2       ]


### 2D Array

In [16]:
var = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
var1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(var)
print(var1)
varadd = np.add(var, var1)
print(varadd)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


### More Arithmetic Functions

Minimum and Maximum

Argmin = index of the minimum
Argmax = index of the maximum

In [24]:
var = np.array([1, 2, 1, 35, 35,4, 5])
print(np.min(var), np.argmin(var))
print(np.max(var), np.argmax(var))

1 0
35 3


In [28]:
var1 = np.array([[1, 2, 3, 4], [5, 6, 7, 1]])
print(np.min(var1, axis = 1)) # axis = 1 means row,    axis = 0 means column

[1 1]


square root

In [29]:
var1 = [1, 4, 9, 16]
print(np.sqrt(var1))

[1. 2. 3. 4.]


sin and cos

In [32]:
var1 = [1, 2, 3, 4]
print(np.sin(var1))
print(np.cos(var1))



[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


log

In [34]:
var1 = [1, 2, 3, 4]
print(np.log(var1)) # natural log
print(np.log2(var1)) # log base 2


[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]


cumsum


In [35]:
var1 = [1, 2, 3, 4] 
print(np.cumsum(var1)) # cumulative sum

[ 1  3  6 10]
