In [2]:
import numpy as np

add(a, b)

In [10]:
var = np.array([1, 2, 3, 4, 5])
varadd = var + 3
varadd2 = var + varadd
print(f"array --> {var}")
print(f"add_array --> {varadd}")
print(f"add_two_arrays --> {varadd2}")

array --> [1 2 3 4 5]
add_array --> [4 5 6 7 8]
add_two_arrays --> [ 5  7  9 11 13]


Subtract - subtract(a, b)

In [15]:
var = np.array([12, 22, 34, 44,53])
varsub = var - 2
varsub2 = var - varsub

print(f"array --> {var}")
print(f"sub_array --> {varsub}")
print(f"sub_two_arrays --> {varsub2}")

array --> [12 22 34 44 53]
sub_array --> [10 20 32 42 51]
sub_two_arrays --> [2 2 2 2 2]


In [20]:
a = np.array([12, 26, 33, 42, 59])
b = np.array([1, 2, 3, 4, 5])

add = np.add(a, b)
sub = np.subtract(a, b)
multiply = np.multiply(a, b)
divide = np.divide(a, b)
exponent = np.exp(b)
square_root= np.sqrt(b)
sin = np.sin(a)
cos = np.cos(b)
log = np.log(a)
dot_product = np.dot(a, b)

print(f"a --> {a}")
print(f"b --> {b}")
print(f"add --> {add}")
print(f"sub --> {sub}")
print(f"multiply --> {multiply}")
print(f"divide --> {divide}")
print(f"exponent --> {exponent}")
print(f"square_root --> {square_root}")
print(f"sin --> {sin}")
print(f"cos --> {cos}")
print(f"log --> {log}")
print(f"dot_product --> {dot_product}")



a --> [12 26 33 42 59]
b --> [1 2 3 4 5]
add --> [13 28 36 46 64]
sub --> [11 24 30 38 54]
multiply --> [ 12  52  99 168 295]
divide --> [12.  13.  11.  10.5 11.8]
exponent --> [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
square_root --> [1.         1.41421356 1.73205081 2.         2.23606798]
sin --> [-0.53657292  0.76255845  0.99991186 -0.91652155  0.63673801]
cos --> [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
log --> [2.48490665 3.25809654 3.49650756 3.73766962 4.07753744]
dot_product --> 626


In [36]:
a = np.array([12, 26, 33, 42, 59])

print(a.sum())
print(a.min())
print(a.max())
print(a.cumsum())
print(a.mean())
print(np.corrcoef(a))
print(a.std())



172
12
59
[ 12  38  71 113 172]
34.4
1.0
15.730225681788548


Multiply - multiply(a, b)

In [8]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varmul = var * var2
print(varmul)


[1 2 3 4 5]
[1 2 3 4 5]
[ 1  4  9 16 25]


Divide - divide(a, b)

In [9]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
vardiv = var / var2
print(vardiv)


[1 2 3 4 5]
[1 2 3 4 5]
[1. 1. 1. 1. 1.]


Power - power(a, b)

In [10]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varpow = var ** var2
print(varpow)

[1 2 3 4 5]
[1 2 3 4 5]
[   1    4   27  256 3125]


Modulo - mod(a, b)

In [11]:
var =   np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
varmod = var % var2
print(varmod)

[1 2 3 4 5]
[1 2 3 4 5]
[0 0 0 0 0]


Reciprocal - reciprocal(a, b)

In [13]:
var = np.array([1, 2, 3, 4, 5])
print(var)
var2 = np.array([1, 2, 3, 4, 5])
print(var2)
# reciprocal
varrec = 1 / var
print(varrec)


[1 2 3 4 5]
[1 2 3 4 5]
[1.         0.5        0.33333333 0.25       0.2       ]


### 2D Array

In [16]:
var = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
var1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(var)
print(var1)
varadd = np.add(var, var1)
print(varadd)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


### More Arithmetic Functions

Minimum and Maximum

Argmin = index of the minimum
Argmax = index of the maximum

In [24]:
var = np.array([1, 2, 1, 35, 35,4, 5])
print(np.min(var), np.argmin(var))
print(np.max(var), np.argmax(var))

1 0
35 3


In [28]:
var1 = np.array([[1, 2, 3, 4], [5, 6, 7, 1]])
print(np.min(var1, axis = 1)) # axis = 1 means row,    axis = 0 means column

[1 1]


square root

In [29]:
var1 = [1, 4, 9, 16]
print(np.sqrt(var1))

[1. 2. 3. 4.]


sin and cos

In [32]:
var1 = [1, 2, 3, 4]
print(np.sin(var1))
print(np.cos(var1))



[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


log

In [34]:
var1 = [1, 2, 3, 4]
print(np.log(var1)) # natural log
print(np.log2(var1)) # log base 2


[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]


cumsum


In [35]:
var1 = [1, 2, 3, 4] 
print(np.cumsum(var1)) # cumulative sum

[ 1  3  6 10]
