In [1]:
import numpy as np

Transpose of an array

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
transpose = a.transpose()
transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

Changing Array Shape

In [12]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
flattened_array = a.ravel()
print(f"\nflattened array--> {flattened_array}")

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

flattened array--> [1 2 3 4 5 6 1 2 3 4 5 6]


Reshaping An Array Without Changing Data

In [39]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
b =a.reshape(3, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
a.resize(5, 3)
a
# resize changes the shape of the array in-place, whereas reshape creates a new array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [40]:
np.append(a, [7, 8, 9])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
np.insert(a, 3, [17, 18, 19])

array([ 1,  2,  3, 17, 18, 19,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15])

In [49]:
b = np.arange(1, 11)
print(b)
np.delete(b, [0, 4, 9]) # delete elements at index 0, 4, and 9

[ 1  2  3  4  5  6  7  8  9 10]


array([2, 3, 4, 6, 7, 8, 9])

In [25]:
var = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(var)
print()
print(var.shape)


[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [10]:
var1 = np.array([1, 2, 3, 4], ndmin = 4)
print(var1)
print(var1.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [26]:
var2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = var2.reshape(2, 2, 2)
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
var2 = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
x = var2.reshape(3, 3)
print(x)

var3 = x.reshape(-1)
print(var3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
