In [1]:
import numpy as np

In [7]:
var = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(var)
print()
print(var.shape)


[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [10]:
var1 = np.array([1, 2, 3, 4], ndmin = 4)
print(var1)
print(var1.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [26]:
var2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = var2.reshape(2, 2, 2)
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
var2 = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
x = var2.reshape(3, 3)
print(x)

var3 = x.reshape(-1)
print(var3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
